version: "3.8"

services:
  lavalink:
    build: .
    container_name: ndlavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    expose:
      - 2333
    ports:
      - "2333:2333"
    networks:
      - ndnetwork

networks:
  ndnetwork:
