version: "3.8"

services:
  lavalink:
    build: .docker/Lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    expose:
      - 2333
    ports:
      - "2333:2333"
  redis:
    build: .docker/Redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
